name: Canary
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  ping:
    name: ping
    runs-on: ubuntu-latest
    steps:
      - name: echo info
        run: |
          echo "Running canary workflow AKA $GITHUB_WORKFLOW on REF $GITHUB_REF SHA $GITHUB_SHA"

